# Default update config
# Config order: hparams_registry -> config.yaml -> CLI
swad: False  # True / False
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 128

# resnet50, resnet50_barlowtwins, resnet50_moco, clip_resnet50, clip_vit-b16, swag_regnety_16gf
model: resnet50
feat_layers: stem_block

# MIRO params
ld: 0.1  # lambda
ld_domain: 0.1
lr_mult: 10.
